language: android
sudo: false
jdk: openjdk7
android:
  components:
    - build-tools-23.0.1
    - extra-android-support
    - extra-android-m2repository
    - android-23
  licenses:
    - '.+'
script:
  - ./gradlew clean assemble check
