language: android
sudo: false
jdk: oraclejdk8
android:
  components:
    - build-tools-21.1.1
    - platform-tools
    - extra-android-support
    - extra-android-m2repository
    - android-21
  licenses:
    - '.+'
